### ISSUE TITLE
Logged in user rush application bug

### ISSUE THREAD

**Issue by samueltallent** [TexasLAN/texaslan.org#11]
When viewing an application of a new user, the user name displayed in the top right becomes the name of the applicant rather than the name of the user who is viewing the application

**Comment by samueltallent** [comment]
![image](https://cloud.githubusercontent.com/assets/9811575/23345477/a91dfee2-fc54-11e6-91bb-15fc87bb286f.png)

becomes

![image](https://cloud.githubusercontent.com/assets/9811575/23345480/ba6b594c-fc54-11e6-8e5f-d8f76125609f.png)

**Comment by DrewRomanyk** [comment]
Handled by: 7eac2a87dd62333d5ae5d83dde9aa5ff976c5197
